"""Advice text templates for all supported languages.

Each template key maps to a list of alternative phrasings.  The advice
engine picks one at random (seeded per hour so it stays stable within the
same coordinator update).  Placeholders use Python ``str.format()`` syntax.

Supported languages: en, nl, de, fr, es.
"""

from __future__ import annotations

# fmt: off

TEMPLATES: dict[str, dict[str, list[str]]] = {

# ════════════════════════════════════════════════════════════════════
#  ENGLISH
# ════════════════════════════════════════════════════════════════════
"en": {

    # ── date / time ─────────────────────────────────────────────
    "day_names":   ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "month_names": ["January", "February", "March", "April", "May", "June",
                    "July", "August", "September", "October", "November", "December"],

    # ── preamble ────────────────────────────────────────────────
    "preamble_location":   ["Advice for {location}, {timestamp}."],
    "preamble_no_location":["Advice generated on {timestamp}."],

    # ── temperature ─────────────────────────────────────────────
    "temp_hot":    ["It's hot — keep it as light as possible.",
                    "High temperatures today — opt for minimal, breathable clothing."],
    "temp_warm":   ["It's warm, a light T-shirt and shorts will do.",
                    "Warm conditions — shorts and a breathable top are ideal."],
    "temp_cool":   ["Mild temperatures, a T-shirt and shorts should be fine.",
                    "Pleasantly cool — a T-shirt is enough for now."],
    "temp_chilly": ["It's on the chilly side — a long-sleeve base layer, 3/4-length tights, and a light jacket are recommended.",
                    "A bit chilly — consider a long-sleeve top with a light layer over it and 3/4-length tights."],
    "temp_cold":   ["Cold conditions — layer up with thermals, full-length tights, fleece, and a windproof jacket.",
                    "It's cold out — thermals, long tights, an insulating mid-layer, and a windproof shell are essential."],
    "temp_freezing":["Freezing temperatures — full winter layers including thermal base, thermal tights, insulating mid, and a windproof outer.",
                     "Well below zero — dress in full winter gear with thermal tights, warm gloves, and head protection."],

    # ── rain ────────────────────────────────────────────────────
    "rain_none":        ["No rain is expected.",
                         "The skies should stay dry."],
    "rain_slight":      ["A slight chance of rain — pack a lightweight shell just in case.",
                         "There's a small chance of showers, so a packable rain jacket could be useful."],
    "rain_likely":      ["Rain is likely ({prob}% chance, ~{mm} {rain_unit}) — bring a waterproof layer.",
                         "Expect rain ({prob}% chance, around {mm} {rain_unit}), a waterproof jacket is essential."],
    "rain_cycling_add": ["Consider waterproof shoe covers for the bike.",
                         "Shoe covers will keep your feet dry while cycling."],

    # ── wind ────────────────────────────────────────────────────
    "wind_calm":          ["Calm wind conditions, very comfortable for outdoor activity.",
                           "Barely any wind — conditions are ideal."],
    "wind_moderate":      ["Moderate wind around {speed} {speed_unit}, but manageable.",
                           "There's a moderate breeze of {speed} {speed_unit} — nothing to worry about."],
    "wind_moderate_bike": ["Moderate wind at {speed} {speed_unit} — a windproof vest helps when cycling.",
                           "With {speed} {speed_unit} wind, a windproof layer makes cycling more comfortable."],
    "wind_strong":        ["Strong wind ({speed} {speed_unit}, gusts up to {gusts} {speed_unit}) — wear a windproof outer layer and stay alert.",
                           "It's very windy ({speed} {speed_unit} with gusts of {gusts} {speed_unit}) — a windproof jacket is a must."],

    # ── cloud + UV combined ─────────────────────────────────────
    "cloud_heavy_uv_low":      ["Heavy clouds and low UV — no sun protection needed.",
                                 "Overcast skies with minimal UV, sun protection isn't necessary today."],
    "cloud_heavy_uv_mod":      ["Despite heavy clouds, UV is moderate — sunscreen is still a good idea.",
                                 "Cloudy but UV still reaches moderate levels, consider sunscreen."],
    "cloud_heavy_uv_high":     ["Even with clouds, UV is high — wear sunscreen and a cap.",
                                 "Don't let the clouds fool you — UV is high, apply sunscreen."],
    "cloud_partial_uv_low":    ["Partly cloudy with low UV. Sunglasses are optional.",
                                 "Some clouds, low UV — sunglasses if you like, but not essential."],
    "cloud_partial_uv_mod":    ["Partly cloudy with moderate UV — wear sunscreen.",
                                 "Moderate UV with some cloud cover — sunscreen recommended."],
    "cloud_partial_uv_high":   ["Partly cloudy but UV is high — sunscreen and a cap are important.",
                                 "Moderate clouds won't block the strong UV — use sunscreen and a hat."],
    "cloud_clear_uv_low":      ["Clear skies with low UV — enjoy the sun without worry.",
                                 "Sunny but UV is low, no special sun protection needed."],
    "cloud_clear_uv_mod":      ["Clear skies and moderate UV — apply sunscreen before heading out.",
                                 "Sunny with moderate UV levels — sunscreen is recommended."],
    "cloud_clear_uv_high":     ["Clear skies and high UV — sunscreen, a cap, and sunglasses are essential.",
                                 "Full sun with high UV — cover up, use sunscreen, and wear a cap."],
    "night_no_uv":              ["It's dark outside — no sun protection needed. Wear something reflective for visibility.",
                                 "Nighttime conditions — UV is not a concern. Consider reflective or high-visibility gear."],
    "sun_sensitivity_warning":  ["Given your sun sensitivity, long sleeves and extra UV protection are advised.",
                                 "Your sun sensitivity means long sleeves and SPF are especially important today."],

    # ── health: all clear ───────────────────────────────────────
    "health_all_clear":  ["No health-related concerns for today's conditions.",
                          "All health indicators look good — enjoy your activity."],

    # ── health: individual conditions ───────────────────────────
    "asthma_pm_high":        ["High particulate matter — consider a face covering or rescheduling your activity.",
                              "Air quality is poor — a face mask is recommended, or consider training indoors."],
    "asthma_cold":           ["Cold, dry air can irritate airways — use a buff or scarf over mouth and nose.",
                              "Protect your airways from the cold with a neck buff or scarf."],
    "asthma_ok":             ["Air quality is good, no extra precautions needed for asthma.",
                              "Air quality looks fine — comfortable conditions for asthma."],
    "pollen_high":           ["High pollen levels — tighter-fitting long sleeves and a shower afterward are recommended.",
                              "Pollen count is elevated — consider long sleeves and rinse off after your session."],
    "pollen_ok":             ["Pollen levels are low, no special precautions needed.",
                              "Pollen count is low — conditions are comfortable."],
    "rheumatism_bad":        ["Low pressure and high humidity may affect your joints — extra warmth for knees and hands is recommended.",
                              "Damp conditions detected — consider thermal knee sleeves and warm gloves for joint comfort."],
    "rheumatism_ok":         ["Pressure and humidity are comfortable for your joints.",
                              "Conditions look joint-friendly today."],
    "hyperhidrosis":         ["With your tendency for heavy perspiration, choose highly breathable fabrics and bring a spare base layer.",
                              "Pack an extra base layer — breathable, moisture-wicking materials will help manage perspiration."],
    "sun_sensitivity_uv":    ["UV levels warrant extra caution — wear UV-protective clothing and long sleeves.",
                              "Your sun sensitivity makes long sleeves and SPF essential today."],
    "cardiovascular_extreme":["Extreme temperatures detected — consider lighter activity or move indoors.",
                              "Temperature is in the danger zone — reduce intensity or exercise indoors for safety."],
    "cardiovascular_ok":     ["Temperature is within a comfortable range for your cardiovascular health.",
                              "No cardiovascular concerns based on today's temperature."],
    "diabetes_advice":       ["Wear well-fitting shoes and moisture-wicking socks to protect your feet.",
                              "Good foot care matters — choose proper footwear and breathable socks."],
    "immunosuppression_bad": ["High pollution or pollen — additional skin coverage is recommended for immunosuppressed individuals.",
                              "Environmental irritants are elevated — cover exposed skin as a precaution."],

    # ── layers (used in attributes) ─────────────────────────────
    "layer_base_singlet":       ["Lightweight moisture-wicking singlet or T-shirt"],
    "layer_base_short":         ["Short-sleeve moisture-wicking T-shirt"],
    "layer_base_long":          ["Long-sleeve base layer"],
    "layer_base_thermal":       ["Thermal long-sleeve base layer"],
    "layer_mid_none":           ["None"],
    "layer_mid_light":          ["Light fleece or running jacket"],
    "layer_mid_insulating":     ["Insulating fleece"],
    "layer_outer_none":         ["None"],
    "layer_outer_windproof":    ["Windproof jacket"],
    "layer_outer_wind_vest":    ["Windproof vest"],
    "layer_outer_rain":         ["Waterproof rain jacket"],
    "acc_gloves":               ["Gloves"],
    "acc_headband":             ["Thermal headband or beanie"],
    "acc_sunglasses":           ["Sunglasses"],
    "acc_cap":                  ["Cap or hat"],
    "acc_sunscreen":            ["Sunscreen SPF 30+"],
    "acc_rain_shoe_covers":     ["Waterproof shoe covers"],
    "acc_face_mask":            ["Breathable face mask"],
    "acc_buff":                 ["Neck buff / scarf"],
    "acc_knee_sleeves":         ["Thermal knee sleeves"],
    "acc_warm_gloves":          ["Warm gloves"],
    "acc_wicking_socks":        ["Moisture-wicking socks"],
    # ── bottoms ──────────────────────────────────────────────────
    "bottom_run_shorts":          ["Running shorts"],
    "bottom_run_34_tights":       ["3/4-length running capris"],
    "bottom_run_tights":          ["Running tights"],
    "bottom_run_thermal_tights":  ["Thermal running tights"],
    "bottom_bike_shorts":         ["Padded cycling shorts / bib shorts"],
    "bottom_bike_34_tights":      ["3/4-length padded cycling tights"],
    "bottom_bike_tights":         ["Padded cycling tights"],
    "bottom_bike_thermal_tights": ["Thermal padded cycling tights"],
    # ── extra accessories ────────────────────────────────────────
    "acc_arm_warmers":            ["Arm warmers"],
    "acc_leg_warmers":            ["Leg warmers"],
    "acc_reflective_vest":        ["Reflective / high-visibility vest"],
},

# ════════════════════════════════════════════════════════════════════
#  DUTCH
# ════════════════════════════════════════════════════════════════════
"nl": {

    "day_names":   ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"],
    "month_names": ["januari", "februari", "maart", "april", "mei", "juni",
                    "juli", "augustus", "september", "oktober", "november", "december"],

    "preamble_location":   ["Advies voor {location}, {timestamp}."],
    "preamble_no_location":["Advies gegenereerd op {timestamp}."],

    "temp_hot":    ["Het is heet — kleed je zo licht mogelijk.",
                    "Hoge temperaturen vandaag — kies voor minimale, ademende kleding."],
    "temp_warm":   ["Het is lekker warm, een T-shirt en korte broek volstaan.",
                    "Warme omstandigheden — een korte broek en licht shirt zijn ideaal."],
    "temp_cool":   ["Aangename temperatuur, een T-shirt en korte broek zijn prima.",
                    "Aangenaam koel — een T-shirt is voldoende."],
    "temp_chilly": ["Het is frisjes — een longsleeve, een driekwart tight en een licht jasje worden aangeraden.",
                    "Beetje fris — trek een longsleeve en driekwart tight aan met een dunne laag erover."],
    "temp_cold":   ["Het is koud — kleed je in lagen met thermokleding, lange tight, fleece en een winddicht jack.",
                    "Koud weer — thermisch ondergoed, lange tight, een isolerende tussenlaag en een winddicht jack zijn nodig."],
    "temp_freezing":["Vriestemperaturen — volledige winterkleding met thermobase, thermische tight, isolerende tussenlaag en winddicht jack.",
                     "Flink onder nul — kleed je volledig in winteruitrusting met thermische tight, warme handschoenen en hoofdbescherming."],

    "rain_none":        ["Er wordt geen regen verwacht.",
                         "Het blijft droog."],
    "rain_slight":      ["Kleine kans op regen — neem voor de zekerheid een lichte regenjas mee.",
                         "Er is een kleine kans op buien, een opvouwbaar regenjack kan handig zijn."],
    "rain_likely":      ["Regen is waarschijnlijk ({prob}% kans, ~{mm} {rain_unit}) — neem een waterafstotende laag mee.",
                         "Verwacht regen ({prob}% kans, ongeveer {mm} {rain_unit}), een waterdicht jack is essentieel."],
    "rain_cycling_add": ["Denk ook aan waterdichte overschoenen op de fiets.",
                         "Overschoenen houden je voeten droog tijdens het fietsen."],

    "wind_calm":          ["Nauwelijks wind — ideale omstandigheden.",
                           "Rustig weer, heel comfortabel voor buiten."],
    "wind_moderate":      ["Matige wind rond {speed} {speed_unit}, maar goed te doen.",
                           "Er staat een matige bries van {speed} {speed_unit} — niets om je zorgen over te maken."],
    "wind_moderate_bike": ["Matige wind van {speed} {speed_unit} — een winddicht vest helpt op de fiets.",
                           "Bij {speed} {speed_unit} wind maakt een winddichte laag het fietsen comfortabeler."],
    "wind_strong":        ["Harde wind ({speed} {speed_unit}, windstoten tot {gusts} {speed_unit}) — draag een winddicht jack en wees voorzichtig.",
                           "Het waait stevig ({speed} {speed_unit} met stoten van {gusts} {speed_unit}) — een winddicht jack is een must."],

    "cloud_heavy_uv_low":      ["Bewolkt met lage UV-straling — geen zonnebescherming nodig.",
                                 "Dikke bewolking en weinig UV, zonnebescherming is vandaag overbodig."],
    "cloud_heavy_uv_mod":      ["Ondanks de bewolking is de UV-straling matig — zonnebrand is verstandig.",
                                 "Bewolkt, maar de UV bereikt nog matige niveaus, overweeg zonnebrand."],
    "cloud_heavy_uv_high":     ["Zelfs met wolken is de UV hoog — smeer je in en draag een pet.",
                                 "Laat je niet misleiden door de wolken — de UV is hoog, breng zonnebrand aan."],
    "cloud_partial_uv_low":    ["Half bewolkt met lage UV. Een zonnebril is optioneel.",
                                 "Wat wolken, lage UV — een zonnebril mag, maar is niet noodzakelijk."],
    "cloud_partial_uv_mod":    ["Half bewolkt met matige UV — smeer zonnebrand.",
                                 "Matige UV met wat bewolking — zonnebrand wordt aangeraden."],
    "cloud_partial_uv_high":   ["Half bewolkt maar hoge UV — zonnebrand en een pet zijn belangrijk.",
                                 "Matige bewolking houdt de sterke UV niet tegen — gebruik zonnebrand en een pet."],
    "cloud_clear_uv_low":      ["Onbewolkt met lage UV — geniet zonder zorgen van de zon.",
                                 "Zonnig maar lage UV, geen speciale bescherming nodig."],
    "cloud_clear_uv_mod":      ["Heldere lucht en matige UV — breng zonnebrand aan voor je vertrekt.",
                                 "Zonnig met matige UV — zonnebrand wordt aanbevolen."],
    "cloud_clear_uv_high":     ["Heldere lucht en hoge UV — zonnebrand, een pet en zonnebril zijn essentieel.",
                                 "Volle zon met hoge UV — bedek je, gebruik zonnebrand en draag een pet."],
    "night_no_uv":              ["Het is donker buiten — geen zonnebescherming nodig. Draag iets reflecterends voor de zichtbaarheid.",
                                 "Nachtelijke omstandigheden — UV is geen probleem. Denk aan reflecterende of opvallende kleding."],
    "sun_sensitivity_warning":  ["Vanwege je zonallergie worden lange mouwen en extra UV-bescherming aangeraden.",
                                 "Je zongevoeligheid maakt lange mouwen en SPF vandaag extra belangrijk."],

    "health_all_clear":  ["Geen gezondheidsgerelateerde aandachtspunten bij deze weersomstandigheden.",
                          "Alle gezondheidsindicatoren zijn goed — geniet van je activiteit."],

    "asthma_pm_high":        ["Veel fijnstof in de lucht — overweeg een mondkapje of stel je training uit.",
                              "Slechte luchtkwaliteit — een mondmasker helpt, of train binnen."],
    "asthma_cold":           ["Koude, droge lucht kan de luchtwegen irriteren — gebruik een buff of sjaal.",
                              "Bescherm je luchtwegen tegen de kou met een nekwarmer of sjaal."],
    "asthma_ok":             ["De luchtkwaliteit is goed, geen extra voorzorgsmaatregelen nodig voor astma.",
                              "De luchtkwaliteit ziet er prima uit — comfortabel voor astma."],
    "pollen_high":           ["Hoog pollenniveau — aansluitende lange mouwen en douchen na de activiteit worden aangeraden.",
                              "Het pollengehalte is verhoogd — overweeg lange mouwen en spoel je af na de sessie."],
    "pollen_ok":             ["Het pollenniveau is laag, geen speciale maatregelen nodig.",
                              "Weinig pollen — comfortabele omstandigheden."],
    "rheumatism_bad":        ["Lage luchtdruk en hoge vochtigheid kunnen je gewrichten beïnvloeden — extra warmte voor knieën en handen wordt aangeraden.",
                              "Vochtige omstandigheden — overweeg thermische kniebeschermers en warme handschoenen."],
    "rheumatism_ok":         ["Luchtdruk en vochtigheid zijn comfortabel voor je gewrichten.",
                              "De omstandigheden zijn vandaag gewrichtsvriendelijk."],
    "hyperhidrosis":         ["Bij je neiging tot overmatig zweten, kies voor zeer ademende stoffen en neem een extra basislaag mee.",
                              "Neem een extra basislaag mee — ademende, vochtafvoerende materialen helpen."],
    "sun_sensitivity_uv":    ["De UV-niveaus vereisen extra voorzichtigheid — draag UV-beschermende kleding en lange mouwen.",
                              "Je zongevoeligheid maakt lange mouwen en SPF vandaag essentieel."],
    "cardiovascular_extreme":["Extreme temperatuur gedetecteerd — overweeg lichtere inspanning of train binnen.",
                              "Temperatuur in de gevarenzone — verminder de intensiteit of sport binnen."],
    "cardiovascular_ok":     ["De temperatuur is comfortabel voor je hart en bloedvaten.",
                              "Geen cardiovasculaire problemen op basis van de temperatuur van vandaag."],
    "diabetes_advice":       ["Draag goed passende schoenen en vochtafvoerende sokken om je voeten te beschermen.",
                              "Goede voetverzorging is belangrijk — kies passend schoeisel en ademende sokken."],
    "immunosuppression_bad": ["Veel vervuiling of pollen — extra huidbedekking wordt aangeraden.",
                              "Omgevingsirritanten zijn verhoogd — bedek blootgestelde huid als voorzorgsmaatregel."],

    "layer_base_singlet":       ["Lichtgewicht vochtafvoerend hemd of T-shirt"],
    "layer_base_short":         ["Kortemouw vochtafvoerend T-shirt"],
    "layer_base_long":          ["Longsleeve basislaag"],
    "layer_base_thermal":       ["Thermische longsleeve basislaag"],
    "layer_mid_none":           ["Geen"],
    "layer_mid_light":          ["Lichte fleece of loopjack"],
    "layer_mid_insulating":     ["Isolerende fleece"],
    "layer_outer_none":         ["Geen"],
    "layer_outer_windproof":    ["Winddicht jack"],
    "layer_outer_wind_vest":    ["Winddicht vest"],
    "layer_outer_rain":         ["Waterdicht regenjack"],
    "acc_gloves":               ["Handschoenen"],
    "acc_headband":             ["Thermische hoofdband of muts"],
    "acc_sunglasses":           ["Zonnebril"],
    "acc_cap":                  ["Pet of hoed"],
    "acc_sunscreen":            ["Zonnebrand SPF 30+"],
    "acc_rain_shoe_covers":     ["Waterdichte overschoenen"],
    "acc_face_mask":            ["Ademend mondmasker"],
    "acc_buff":                 ["Nekwarmer / sjaal"],
    "acc_knee_sleeves":         ["Thermische kniebeschermers"],
    "acc_warm_gloves":          ["Warme handschoenen"],
    "acc_wicking_socks":        ["Vochtafvoerende sokken"],
    "bottom_run_shorts":          ["Hardloopbroekje"],
    "bottom_run_34_tights":       ["3/4 hardlooptight"],
    "bottom_run_tights":          ["Hardlooptight"],
    "bottom_run_thermal_tights":  ["Thermische hardlooptight"],
    "bottom_bike_shorts":         ["Gewatteerde fietsbroek / koersbroek"],
    "bottom_bike_34_tights":      ["3/4 gewatteerde fietstight"],
    "bottom_bike_tights":         ["Gewatteerde fietstight"],
    "bottom_bike_thermal_tights": ["Thermische gewatteerde fietstight"],
    "acc_arm_warmers":            ["Armwarmers"],
    "acc_leg_warmers":            ["Beenwarmers"],
    "acc_reflective_vest":        ["Reflecterend / zichtbaarheidsvest"],
},

# ════════════════════════════════════════════════════════════════════
#  GERMAN
# ════════════════════════════════════════════════════════════════════
"de": {

    "day_names":   ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
    "month_names": ["Januar", "Februar", "März", "April", "Mai", "Juni",
                    "Juli", "August", "September", "Oktober", "November", "Dezember"],

    "preamble_location":   ["Empfehlung für {location}, {timestamp}."],
    "preamble_no_location":["Empfehlung erstellt am {timestamp}."],

    "temp_hot":    ["Es ist heiß — trage so wenig wie möglich.",
                    "Hohe Temperaturen heute — wähle minimale, atmungsaktive Kleidung."],
    "temp_warm":   ["Angenehm warm, mit T-Shirt und kurzer Hose bist du gut angezogen.",
                    "Warme Bedingungen — kurze Hose und ein leichtes Oberteil sind ideal."],
    "temp_cool":   ["Milde Temperaturen — ein T-Shirt und kurze Hose reichen aus.",
                    "Angenehm kühl — ein T-Shirt genügt."],
    "temp_chilly": ["Es ist kühl — ein Langarmshirt, eine 3/4-Tight und eine leichte Jacke werden empfohlen.",
                    "Etwas frisch — ziehe ein Langarmshirt und eine 3/4-Tight mit einer dünnen Schicht darüber an."],
    "temp_cold":   ["Kalt — ziehe dich mit Thermokleidung, langer Tight, Fleece und winddichter Jacke warm an.",
                    "Kaltes Wetter — Thermounterwäsche, lange Tight, isolierende Mittelschicht und winddichte Jacke sind nötig."],
    "temp_freezing":["Frost — komplette Winterausrüstung mit Thermobase, Thermotight, isolierender Mittelschicht und winddichter Außenschicht.",
                     "Deutlich unter null — ziehe dich mit kompletter Winterausrüstung, Thermotight, Handschuhen und Kopfschutz an."],

    "rain_none":        ["Es wird kein Regen erwartet.",
                         "Der Himmel bleibt trocken."],
    "rain_slight":      ["Geringe Regenwahrscheinlichkeit — für alle Fälle eine leichte Regenjacke einpacken.",
                         "Eine kleine Chance auf Schauer, eine packbare Regenjacke könnte nützlich sein."],
    "rain_likely":      ["Regen ist wahrscheinlich ({prob}% Chance, ~{mm} {rain_unit}) — eine wasserdichte Schicht mitnehmen.",
                         "Regen erwartet ({prob}% Chance, circa {mm} {rain_unit}), eine Regenjacke ist unerlässlich."],
    "rain_cycling_add": ["Wasserdichte Überschuhe schützen die Füße beim Radfahren.",
                         "Überschuhe halten deine Füße beim Radeln trocken."],

    "wind_calm":          ["Kaum Wind — ideale Bedingungen.",
                           "Ruhiges Wetter, sehr angenehm für draußen."],
    "wind_moderate":      ["Mäßiger Wind um {speed} {speed_unit}, aber gut zu bewältigen.",
                           "Eine mäßige Brise von {speed} {speed_unit} — kein Grund zur Sorge."],
    "wind_moderate_bike": ["Mäßiger Wind mit {speed} {speed_unit} — eine Windweste hilft beim Radfahren.",
                           "Bei {speed} {speed_unit} Wind macht eine winddichte Schicht das Radfahren angenehmer."],
    "wind_strong":        ["Starker Wind ({speed} {speed_unit}, Böen bis {gusts} {speed_unit}) — windddichte Jacke tragen und vorsichtig sein.",
                           "Es ist sehr windig ({speed} {speed_unit} mit Böen von {gusts} {speed_unit}) — eine winddichte Jacke ist ein Muss."],

    "cloud_heavy_uv_low":      ["Stark bewölkt mit niedrigem UV — kein Sonnenschutz nötig.",
                                 "Dichte Wolken und wenig UV, Sonnenschutz ist heute nicht erforderlich."],
    "cloud_heavy_uv_mod":      ["Trotz Bewölkung ist der UV-Index mäßig — Sonnencreme bleibt sinnvoll.",
                                 "Bewölkt, aber UV erreicht noch mäßige Werte, Sonnencreme wird empfohlen."],
    "cloud_heavy_uv_high":     ["Auch bei Wolken ist der UV-Index hoch — Sonnencreme und Kappe tragen.",
                                 "Lass dich nicht von den Wolken täuschen — der UV-Index ist hoch."],
    "cloud_partial_uv_low":    ["Teilweise bewölkt mit niedrigem UV. Sonnenbrille optional.",
                                 "Etwas Wolken, niedriger UV — Sonnenbrille möglich, aber nicht nötig."],
    "cloud_partial_uv_mod":    ["Teilweise bewölkt mit mäßigem UV — Sonnencreme auftragen.",
                                 "Mäßiger UV bei etwas Bewölkung — Sonnencreme empfohlen."],
    "cloud_partial_uv_high":   ["Teilweise bewölkt aber hoher UV — Sonnencreme und Kappe sind wichtig.",
                                 "Mäßige Wolken halten den starken UV nicht ab — Sonnencreme und Hut benutzen."],
    "cloud_clear_uv_low":      ["Klarer Himmel mit niedrigem UV — genieße die Sonne ohne Bedenken.",
                                 "Sonnig aber niedriger UV, kein besonderer Schutz nötig."],
    "cloud_clear_uv_mod":      ["Klarer Himmel und mäßiger UV — Sonnencreme vor dem Aufbruch auftragen.",
                                 "Sonnig mit mäßigem UV — Sonnencreme empfohlen."],
    "cloud_clear_uv_high":     ["Klarer Himmel und hoher UV — Sonnencreme, Kappe und Sonnenbrille sind notwendig.",
                                 "Volle Sonne mit hohem UV — eincremen, Kappe und Sonnenbrille tragen."],
    "night_no_uv":              ["Es ist dunkel — kein Sonnenschutz nötig. Trage etwas Reflektierendes für die Sichtbarkeit.",
                                 "Nachtbedingungen — UV ist kein Thema. Denke an reflektierende oder gut sichtbare Kleidung."],
    "sun_sensitivity_warning":  ["Wegen deiner Sonnenempfindlichkeit werden lange Ärmel und extra UV-Schutz empfohlen.",
                                 "Deine Sonnenempfindlichkeit macht lange Ärmel und hohen Lichtschutzfaktor heute besonders wichtig."],

    "health_all_clear":  ["Keine gesundheitlichen Bedenken bei den heutigen Bedingungen.",
                          "Alle Gesundheitsindikatoren sehen gut aus — viel Spaß bei deinem Training."],

    "asthma_pm_high":        ["Hohe Feinstaubbelastung — erwäge einen Mundschutz oder verschiebe das Training.",
                              "Schlechte Luftqualität — eine Atemmaske wird empfohlen oder trainiere drinnen."],
    "asthma_cold":           ["Kalte, trockene Luft kann die Atemwege reizen — nutze ein Tuch oder einen Schal.",
                              "Schütze deine Atemwege mit einem Halstuch oder Schal vor der Kälte."],
    "asthma_ok":             ["Die Luftqualität ist gut, keine besonderen Maßnahmen bei Asthma nötig.",
                              "Die Luft ist unbedenklich — komfortable Bedingungen bei Asthma."],
    "pollen_high":           ["Hohe Pollenbelastung — eng anliegende lange Ärmel und Duschen danach empfohlen.",
                              "Pollenflug ist erhöht — erwäge lange Ärmel und spüle dich nach dem Training ab."],
    "pollen_ok":             ["Pollenbelastung ist niedrig, keine speziellen Maßnahmen nötig.",
                              "Wenig Pollen — komfortable Bedingungen."],
    "rheumatism_bad":        ["Niedriger Luftdruck und hohe Feuchtigkeit können deine Gelenke beeinträchtigen — extra Wärme für Knie und Hände empfohlen.",
                              "Feuchte Bedingungen — thermische Knieschoner und warme Handschuhe werden empfohlen."],
    "rheumatism_ok":         ["Luftdruck und Luftfeuchtigkeit sind angenehm für deine Gelenke.",
                              "Gelenkfreundliche-Bedingungen heute."],
    "hyperhidrosis":         ["Bei deiner Neigung zu starkem Schwitzen, wähle hochatmungsaktive Stoffe und nimm eine Ersatzbasisschicht mit.",
                              "Packe eine Extra-Basisschicht ein — atmungsaktive Materialien helfen bei Transpiration."],
    "sun_sensitivity_uv":    ["Die UV-Werte erfordern extra Vorsicht — trage UV-Schutzkleidung und lange Ärmel.",
                              "Deine Sonnenempfindlichkeit macht lange Ärmel und LSF heute unerlässlich."],
    "cardiovascular_extreme":["Extreme Temperatur — erwäge leichtere Aktivität oder trainiere drinnen.",
                              "Temperatur im Gefahrenbereich — Intensität reduzieren oder drinnen trainieren."],
    "cardiovascular_ok":     ["Die Temperatur liegt im angenehmen Bereich für Herz und Kreislauf.",
                              "Keine kardiovaskulären Bedenken bei der heutigen Temperatur."],
    "diabetes_advice":       ["Trage gut sitzende Schuhe und feuchtigkeitsableitende Socken zum Schutz deiner Füße.",
                              "Gute Fußpflege ist wichtig — wähle passendes Schuhwerk und atmungsaktive Socken."],
    "immunosuppression_bad": ["Hohe Schadstoff- oder Pollenbelastung — zusätzliche Hautbedeckung empfohlen.",
                              "Umweltirritanten sind erhöht — bedecke exponierte Haut als Vorsichtsmaßnahme."],

    "layer_base_singlet":       ["Leichtes feuchtigkeitsableitendes Unterhemd oder T-Shirt"],
    "layer_base_short":         ["Kurzarm feuchtigkeitsableitendes T-Shirt"],
    "layer_base_long":          ["Langarm Basisschicht"],
    "layer_base_thermal":       ["Thermische Langarm-Basisschicht"],
    "layer_mid_none":           ["Keine"],
    "layer_mid_light":          ["Leichter Fleece oder Laufjacke"],
    "layer_mid_insulating":     ["Isolierender Fleece"],
    "layer_outer_none":         ["Keine"],
    "layer_outer_windproof":    ["Winddichte Jacke"],
    "layer_outer_wind_vest":    ["Winddichte Weste"],
    "layer_outer_rain":         ["Wasserdichte Regenjacke"],
    "acc_gloves":               ["Handschuhe"],
    "acc_headband":             ["Thermisches Stirnband oder Mütze"],
    "acc_sunglasses":           ["Sonnenbrille"],
    "acc_cap":                  ["Kappe oder Hut"],
    "acc_sunscreen":            ["Sonnencreme LSF 30+"],
    "acc_rain_shoe_covers":     ["Wasserdichte Überschuhe"],
    "acc_face_mask":            ["Atmungsaktive Gesichtsmaske"],
    "acc_buff":                 ["Halstuch / Schal"],
    "acc_knee_sleeves":         ["Thermische Knieschoner"],
    "acc_warm_gloves":          ["Warme Handschuhe"],
    "acc_wicking_socks":        ["Feuchtigkeitsableitende Socken"],
    "bottom_run_shorts":          ["Laufshorts"],
    "bottom_run_34_tights":       ["3/4-Lauftight"],
    "bottom_run_tights":          ["Lauftight"],
    "bottom_run_thermal_tights":  ["Thermische Lauftight"],
    "bottom_bike_shorts":         ["Gepolsterte Radhose / Trägerhose"],
    "bottom_bike_34_tights":      ["3/4 gepolsterte Radtight"],
    "bottom_bike_tights":         ["Gepolsterte Radtight"],
    "bottom_bike_thermal_tights": ["Thermische gepolsterte Radtight"],
    "acc_arm_warmers":            ["Armlinge"],
    "acc_leg_warmers":            ["Beinlinge"],
    "acc_reflective_vest":        ["Reflektierende / Warnweste"],
},

# ════════════════════════════════════════════════════════════════════
#  FRENCH
# ════════════════════════════════════════════════════════════════════
"fr": {

    "day_names":   ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
    "month_names": ["janvier", "février", "mars", "avril", "mai", "juin",
                    "juillet", "août", "septembre", "octobre", "novembre", "décembre"],

    "preamble_location":   ["Conseils pour {location}, {timestamp}."],
    "preamble_no_location":["Conseils générés le {timestamp}."],

    "temp_hot":    ["Il fait chaud — habillez-vous le plus légèrement possible.",
                    "Températures élevées — optez pour des vêtements légers et respirants."],
    "temp_warm":   ["Il fait bon, un T-shirt et un short suffisent.",
                    "Temps chaud — un short et un haut léger sont parfaits."],
    "temp_cool":   ["Températures agréables, un T-shirt et un short conviennent.",
                    "Agréablement frais — un T-shirt suffit."],
    "temp_chilly": ["Il fait frais — une couche de base à manches longues, un corsaire 3/4 et une veste légère sont recommandés.",
                    "Un peu frais — enfilez un haut à manches longues et un corsaire 3/4 avec une fine couche par-dessus."],
    "temp_cold":   ["Il fait froid — superposez les couches avec sous-vêtements thermiques, collant long, polaire et veste coupe-vent.",
                    "Temps froid — sous-vêtements thermiques, collant long, couche isolante et coupe-vent sont indispensables."],
    "temp_freezing":["Températures glaciales — tenue complète d'hiver avec base thermique, collant thermique, couche isolante et coupe-vent.",
                     "Bien en-dessous de zéro — habillez-vous en tenue d'hiver complète avec collant thermique, gants et protection pour la tête."],

    "rain_none":        ["Aucune pluie prévue.",
                         "Le ciel devrait rester sec."],
    "rain_slight":      ["Légère possibilité de pluie — emportez un coupe-vent léger par précaution.",
                         "Faible chance d'averses, une veste de pluie pliable peut être utile."],
    "rain_likely":      ["Pluie probable ({prob}% de chance, ~{mm} {rain_unit}) — prenez une couche imperméable.",
                         "Attendez-vous à la pluie ({prob}% de chance, environ {mm} {rain_unit}), une veste imperméable est essentielle."],
    "rain_cycling_add": ["Pensez aux surchaussures imperméables pour le vélo.",
                         "Les surchaussures garderont vos pieds au sec en pédalant."],

    "wind_calm":          ["Peu de vent — conditions idéales.",
                           "Temps calme, très confortable pour l'extérieur."],
    "wind_moderate":      ["Vent modéré autour de {speed} {speed_unit}, mais gérable.",
                           "Brise modérée de {speed} {speed_unit} — rien d'inquiétant."],
    "wind_moderate_bike": ["Vent modéré à {speed} {speed_unit} — un gilet coupe-vent aide en vélo.",
                           "Avec {speed} {speed_unit} de vent, une couche coupe-vent rend le vélo plus confortable."],
    "wind_strong":        ["Vent fort ({speed} {speed_unit}, rafales jusqu'à {gusts} {speed_unit}) — portez une veste coupe-vent et restez prudent.",
                           "Très venteux ({speed} {speed_unit} avec rafales de {gusts} {speed_unit}) — un coupe-vent est indispensable."],

    "cloud_heavy_uv_low":      ["Ciel très couvert avec un UV faible — pas besoin de protection solaire.",
                                 "Nuages épais et UV minimal, la protection solaire n'est pas nécessaire aujourd'hui."],
    "cloud_heavy_uv_mod":      ["Malgré la couverture nuageuse, l'UV est modéré — la crème solaire reste conseillée.",
                                 "Nuageux mais l'UV atteint encore des niveaux modérés, pensez à la crème solaire."],
    "cloud_heavy_uv_high":     ["Même avec les nuages, l'UV est élevé — appliquez de la crème solaire et portez une casquette.",
                                 "Ne vous fiez pas aux nuages — l'UV est élevé, mettez de la crème solaire."],
    "cloud_partial_uv_low":    ["Partiellement nuageux, UV faible. Lunettes de soleil optionnelles.",
                                 "Quelques nuages, UV faible — lunettes de soleil si vous voulez, mais pas indispensables."],
    "cloud_partial_uv_mod":    ["Partiellement nuageux, UV modéré — appliquez de la crème solaire.",
                                 "UV modéré avec quelques nuages — crème solaire recommandée."],
    "cloud_partial_uv_high":   ["Partiellement nuageux mais UV élevé — crème solaire et casquette sont importants.",
                                 "Les nuages ne bloquent pas le fort UV — utilisez crème solaire et chapeau."],
    "cloud_clear_uv_low":      ["Ciel dégagé avec UV faible — profitez du soleil sans souci.",
                                 "Ensoleillé mais UV faible, pas de protection spéciale nécessaire."],
    "cloud_clear_uv_mod":      ["Ciel dégagé et UV modéré — appliquez de la crème solaire avant de partir.",
                                 "Ensoleillé avec UV modéré — crème solaire recommandée."],
    "cloud_clear_uv_high":     ["Ciel dégagé et UV élevé — crème solaire, casquette et lunettes sont essentiels.",
                                 "Plein soleil avec UV élevé — protégez-vous, crème solaire et casquette obligatoires."],
    "night_no_uv":              ["Il fait nuit — pas besoin de protection solaire. Portez quelque chose de réfléchissant pour la visibilité.",
                                 "Conditions nocturnes — les UV ne sont pas un souci. Pensez à un équipement réfléchissant ou haute visibilité."],
    "sun_sensitivity_warning":  ["En raison de votre sensibilité au soleil, les manches longues et une protection UV supplémentaire sont conseillées.",
                                 "Votre photosensibilité rend les manches longues et le SPF particulièrement importants aujourd'hui."],

    "health_all_clear":  ["Aucune préoccupation de santé pour les conditions d'aujourd'hui.",
                          "Tous les indicateurs de santé sont bons — profitez de votre activité."],

    "asthma_pm_high":        ["Forte concentration de particules fines — envisagez un masque ou reportez votre activité.",
                              "Qualité de l'air médiocre — un masque est recommandé ou entraînez-vous à l'intérieur."],
    "asthma_cold":           ["L'air froid et sec peut irriter les voies respiratoires — utilisez un tour de cou ou une écharpe.",
                              "Protégez vos voies respiratoires du froid avec un cache-cou ou une écharpe."],
    "asthma_ok":             ["La qualité de l'air est bonne, pas de précaution spéciale pour l'asthme.",
                              "L'air est sain — conditions confortables pour l'asthme."],
    "pollen_high":           ["Niveaux de pollen élevés — manches longues ajustées et douche après l'activité recommandées.",
                              "Le taux de pollen est élevé — pensez aux manches longues et rincez-vous après la séance."],
    "pollen_ok":             ["Niveaux de pollen bas, pas de précaution spéciale nécessaire.",
                              "Peu de pollen — conditions confortables."],
    "rheumatism_bad":        ["Basse pression et forte humidité peuvent affecter vos articulations — chaleur supplémentaire pour genoux et mains recommandée.",
                              "Conditions humides — envisagez des manchons thermiques pour les genoux et des gants chauds."],
    "rheumatism_ok":         ["Pression et humidité confortables pour vos articulations.",
                              "Conditions favorables pour vos articulations aujourd'hui."],
    "hyperhidrosis":         ["Avec votre tendance à transpirer abondamment, choisissez des tissus très respirants et emportez une couche de base de rechange.",
                              "Emportez une couche de base supplémentaire — les matériaux respirants aideront à gérer la transpiration."],
    "sun_sensitivity_uv":    ["Les niveaux d'UV nécessitent une prudence accrue — portez des vêtements anti-UV et des manches longues.",
                              "Votre photosensibilité rend les manches longues et le SPF essentiels aujourd'hui."],
    "cardiovascular_extreme":["Température extrême — envisagez une activité plus légère ou faites du sport à l'intérieur.",
                              "Température dans la zone de danger — réduisez l'intensité ou entraînez-vous en intérieur."],
    "cardiovascular_ok":     ["La température est dans une plage confortable pour la santé cardiovasculaire.",
                              "Pas de préoccupation cardiovasculaire avec la température d'aujourd'hui."],
    "diabetes_advice":       ["Portez des chaussures bien ajustées et des chaussettes évacuant l'humidité pour protéger vos pieds.",
                              "Un bon soin des pieds est important — choisissez des chaussures adaptées et des chaussettes respirantes."],
    "immunosuppression_bad": ["Pollution ou pollen élevés — une couverture cutanée supplémentaire est recommandée.",
                              "Les irritants environnementaux sont élevés — couvrez la peau exposée par précaution."],

    "layer_base_singlet":       ["Débardeur léger ou T-shirt évacuant l'humidité"],
    "layer_base_short":         ["T-shirt manches courtes évacuant l'humidité"],
    "layer_base_long":          ["Couche de base manches longues"],
    "layer_base_thermal":       ["Couche de base thermique manches longues"],
    "layer_mid_none":           ["Aucune"],
    "layer_mid_light":          ["Polaire légère ou veste de course"],
    "layer_mid_insulating":     ["Polaire isolante"],
    "layer_outer_none":         ["Aucune"],
    "layer_outer_windproof":    ["Veste coupe-vent"],
    "layer_outer_wind_vest":    ["Gilet coupe-vent"],
    "layer_outer_rain":         ["Veste de pluie imperméable"],
    "acc_gloves":               ["Gants"],
    "acc_headband":             ["Bandeau thermique ou bonnet"],
    "acc_sunglasses":           ["Lunettes de soleil"],
    "acc_cap":                  ["Casquette ou chapeau"],
    "acc_sunscreen":            ["Crème solaire SPF 30+"],
    "acc_rain_shoe_covers":     ["Surchaussures imperméables"],
    "acc_face_mask":            ["Masque respirant"],
    "acc_buff":                 ["Tour de cou / écharpe"],
    "acc_knee_sleeves":         ["Manchons thermiques pour genoux"],
    "acc_warm_gloves":          ["Gants chauds"],
    "acc_wicking_socks":        ["Chaussettes évacuant l'humidité"],
    "bottom_run_shorts":          ["Short de course"],
    "bottom_run_34_tights":       ["Corsaire de course 3/4"],
    "bottom_run_tights":          ["Collant de course"],
    "bottom_run_thermal_tights":  ["Collant thermique de course"],
    "bottom_bike_shorts":         ["Cuissard rembourré / cuissard à bretelles"],
    "bottom_bike_34_tights":      ["Corsaire rembourré 3/4"],
    "bottom_bike_tights":         ["Collant rembourré de cyclisme"],
    "bottom_bike_thermal_tights": ["Collant thermique rembourré de cyclisme"],
    "acc_arm_warmers":            ["Manchettes"],
    "acc_leg_warmers":            ["Jambières"],
    "acc_reflective_vest":        ["Gilet réfléchissant / haute visibilité"],
},

# ════════════════════════════════════════════════════════════════════
#  SPANISH
# ════════════════════════════════════════════════════════════════════
"es": {

    "day_names":   ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"],
    "month_names": ["enero", "febrero", "marzo", "abril", "mayo", "junio",
                    "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],

    "preamble_location":   ["Consejo para {location}, {timestamp}."],
    "preamble_no_location":["Consejo generado el {timestamp}."],

    "temp_hot":    ["Hace mucho calor — viste lo más ligero posible.",
                    "Temperaturas altas hoy — elige ropa mínima y transpirable."],
    "temp_warm":   ["Hace calor, con camiseta y pantalón corto irás bien.",
                    "Condiciones cálidas — pantalón corto y una camiseta ligera son ideales."],
    "temp_cool":   ["Temperatura agradable, camiseta y pantalón corto son suficientes.",
                    "Agradablemente fresco — una camiseta es necesario."],
    "temp_chilly": ["Hace fresco — se recomienda manga larga, mallas 3/4 y una chaqueta ligera.",
                    "Un poco frío — ponte manga larga y mallas 3/4 con una fina capa encima."],
    "temp_cold":   ["Hace frío — abrígate con ropa térmica, mallas largas, forro polar y chaqueta cortavientos.",
                    "Clima frío — ropa interior térmica, mallas largas, capa aislante y cortavientos son necesarios."],
    "temp_freezing":["Temperaturas bajo cero — equipación completa de invierno con base térmica, mallas térmicas, capa aislante y cortavientos.",
                     "Muy por debajo de cero — vístete con equipo de invierno completo con mallas térmicas, guantes y protección para la cabeza."],

    "rain_none":        ["No se espera lluvia.",
                         "El cielo debería mantenerse seco."],
    "rain_slight":      ["Ligera posibilidad de lluvia — lleva un chubasquero ligero por si acaso.",
                         "Pequeña posibilidad de chubascos, un impermeable plegable puede ser útil."],
    "rain_likely":      ["Lluvia probable ({prob}% de probabilidad, ~{mm} {rain_unit}) — lleva una capa impermeable.",
                         "Se espera lluvia ({prob}% de probabilidad, unos {mm} {rain_unit}), un impermeable es esencial."],
    "rain_cycling_add": ["Considera cubrezapatillas impermeables para la bici.",
                         "Los cubrezapatillas mantendrán tus pies secos pedaleando."],

    "wind_calm":          ["Apenas hay viento — condiciones ideales.",
                           "Tiempo tranquilo, muy cómodo para actividades al aire libre."],
    "wind_moderate":      ["Viento moderado de unos {speed} {speed_unit}, pero manejable.",
                           "Brisa moderada de {speed} {speed_unit} — nada preocupante."],
    "wind_moderate_bike": ["Viento moderado de {speed} {speed_unit} — un chaleco cortavientos ayuda en bici.",
                           "Con {speed} {speed_unit} de viento, una prenda cortavientos hace más cómodo el ciclismo."],
    "wind_strong":        ["Viento fuerte ({speed} {speed_unit}, rachas de {gusts} {speed_unit}) — usa chaqueta cortavientos y ten cuidado.",
                           "Mucho viento ({speed} {speed_unit} con rachas de {gusts} {speed_unit}) — un cortavientos es imprescindible."],

    "cloud_heavy_uv_low":      ["Muy nublado con UV bajo — no necesitas protección solar.",
                                 "Nubes densas y UV mínimo, la protección solar no es necesaria hoy."],
    "cloud_heavy_uv_mod":      ["A pesar de la nubosidad, el UV es moderado — la crema solar sigue siendo buena idea.",
                                 "Nublado pero el UV alcanza niveles moderados, considera usar crema solar."],
    "cloud_heavy_uv_high":     ["Incluso con nubes, el UV es alto — aplica crema solar y usa gorra.",
                                 "No te dejes engañar por las nubes — el UV es alto, ponte crema solar."],
    "cloud_partial_uv_low":    ["Parcialmente nublado con UV bajo. Gafas de sol opcionales.",
                                 "Algunas nubes, UV bajo — gafas de sol si quieres, pero no imprescindibles."],
    "cloud_partial_uv_mod":    ["Parcialmente nublado con UV moderado — aplica crema solar.",
                                 "UV moderado con algo de nubosidad — se recomienda crema solar."],
    "cloud_partial_uv_high":   ["Parcialmente nublado pero UV alto — crema solar y gorra son importantes.",
                                 "Las nubes parciales no bloquean el fuerte UV — usa crema solar y sombrero."],
    "cloud_clear_uv_low":      ["Cielo despejado con UV bajo — disfruta del sol sin preocupaciones.",
                                 "Soleado pero UV bajo, no necesitas protección solar especial."],
    "cloud_clear_uv_mod":      ["Cielo despejado y UV moderado — aplica crema solar antes de salir.",
                                 "Soleado con UV moderado — se recomienda crema solar."],
    "cloud_clear_uv_high":     ["Cielo despejado y UV alto — crema solar, gorra y gafas de sol son esenciales.",
                                 "Sol directo con UV alto — protégete, crema solar y gorra obligatorias."],
    "night_no_uv":              ["Está oscuro — no necesitas protección solar. Usa algo reflectante para ser visible.",
                                 "Condiciones nocturnas — los UV no son un problema. Considera ropa reflectante o de alta visibilidad."],
    "sun_sensitivity_warning":  ["Por tu sensibilidad solar, se recomiendan mangas largas y protección UV extra.",
                                 "Tu fotosensibilidad hace especialmente importantes las mangas largas y el SPF hoy."],

    "health_all_clear":  ["Sin preocupaciones de salud para las condiciones de hoy.",
                          "Todos los indicadores de salud están bien — disfruta de tu actividad."],

    "asthma_pm_high":        ["Alta concentración de partículas — considera una mascarilla o pospón tu actividad.",
                              "Calidad del aire deficiente — se recomienda mascarilla o entrenar en interior."],
    "asthma_cold":           ["El aire frío y seco puede irritar las vías respiratorias — usa un buff o bufanda.",
                              "Protege tus vías respiratorias del frío con un buff o bufanda."],
    "asthma_ok":             ["La calidad del aire es buena, sin precauciones especiales para el asma.",
                              "El aire está bien — condiciones cómodas para el asma."],
    "pollen_high":           ["Niveles altos de polen — mangas largas ajustadas y ducha después de la actividad recomendadas.",
                              "El recuento de polen es alto — considera mangas largas y enjuágate después de la sesión."],
    "pollen_ok":             ["Niveles de polen bajos, sin precauciones especiales necesarias.",
                              "Poco polen — condiciones cómodas."],
    "rheumatism_bad":        ["Baja presión y alta humedad pueden afectar tus articulaciones — se recomienda calor extra para rodillas y manos.",
                              "Condiciones húmedas — considera rodilleras térmicas y guantes calientes."],
    "rheumatism_ok":         ["Presión y humedad cómodas para tus articulaciones.",
                              "Condiciones favorables para las articulaciones hoy."],
    "hyperhidrosis":         ["Con tu tendencia a sudar mucho, elige tejidos muy transpirables y lleva una capa base de repuesto.",
                              "Lleva una capa base extra — los materiales transpirables ayudarán con la transpiración."],
    "sun_sensitivity_uv":    ["Los niveles de UV requieren precaución extra — usa ropa con protección UV y mangas largas.",
                              "Tu fotosensibilidad hace esenciales las mangas largas y el SPF hoy."],
    "cardiovascular_extreme":["Temperatura extrema — considera actividad más ligera o hacer ejercicio en interior.",
                              "Temperatura en zona de peligro — reduce la intensidad o entrena en interior."],
    "cardiovascular_ok":     ["La temperatura está en un rango cómodo para tu salud cardiovascular.",
                              "Sin preocupaciones cardiovasculares con la temperatura de hoy."],
    "diabetes_advice":       ["Usa calzado bien ajustado y calcetines que absorban la humedad para proteger tus pies.",
                              "El cuidado de los pies es importante — elige calzado adecuado y calcetines transpirables."],
    "immunosuppression_bad": ["Alta contaminación o polen — se recomienda cubrir más la piel.",
                              "Los irritantes ambientales están elevados — cubre la piel expuesta como precaución."],

    "layer_base_singlet":       ["Camiseta de tirantes ligera o camiseta transpirable"],
    "layer_base_short":         ["Camiseta de manga corta transpirable"],
    "layer_base_long":          ["Capa base de manga larga"],
    "layer_base_thermal":       ["Capa base térmica de manga larga"],
    "layer_mid_none":           ["Ninguna"],
    "layer_mid_light":          ["Forro polar ligero o chaqueta de correr"],
    "layer_mid_insulating":     ["Forro polar aislante"],
    "layer_outer_none":         ["Ninguna"],
    "layer_outer_windproof":    ["Chaqueta cortavientos"],
    "layer_outer_wind_vest":    ["Chaleco cortavientos"],
    "layer_outer_rain":         ["Chaqueta impermeable"],
    "acc_gloves":               ["Guantes"],
    "acc_headband":             ["Cinta térmica o gorro"],
    "acc_sunglasses":           ["Gafas de sol"],
    "acc_cap":                  ["Gorra o sombrero"],
    "acc_sunscreen":            ["Protector solar SPF 30+"],
    "acc_rain_shoe_covers":     ["Cubrezapatillas impermeables"],
    "acc_face_mask":            ["Mascarilla transpirable"],
    "acc_buff":                 ["Buff / bufanda"],
    "acc_knee_sleeves":         ["Rodilleras térmicas"],
    "acc_warm_gloves":          ["Guantes calientes"],
    "acc_wicking_socks":        ["Calcetines transpirables"],
    "bottom_run_shorts":          ["Pantalón corto de running"],
    "bottom_run_34_tights":       ["Mallas 3/4 de running"],
    "bottom_run_tights":          ["Mallas de running"],
    "bottom_run_thermal_tights":  ["Mallas térmicas de running"],
    "bottom_bike_shorts":         ["Culote acolchado / culote con tirantes"],
    "bottom_bike_34_tights":      ["Mallas 3/4 acolchadas de ciclismo"],
    "bottom_bike_tights":         ["Mallas acolchadas de ciclismo"],
    "bottom_bike_thermal_tights": ["Mallas térmicas acolchadas de ciclismo"],
    "acc_arm_warmers":            ["Manguitos"],
    "acc_leg_warmers":            ["Perneras"],
    "acc_reflective_vest":        ["Chaleco reflectante / alta visibilidad"],
},

}

# fmt: on


def get_templates(language: str) -> dict[str, list[str]]:
    """Return templates for *language*, falling back to English."""
    lang = language[:2].lower()  # "nl" from "nl", "en-GB" → "en"
    return TEMPLATES.get(lang, TEMPLATES["en"])
